---
title: "Molecular Mechanisms for Human Diseases: Lab 1"
subtitle: "Bacteria's Brain -- Part A"
output:
  github_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
theme_set(theme_minimal())
```

Data: Here we start by importing data from csv files

```{r import data}
#import A;
novick_a <- read.csv("data/g149novickA.csv", header = FALSE) 
novick_a <- novick_a %>%   
  # separate columns and add titles;
  separate_wider_delim(1, ",", names = c("t", "concentration")) %>%
  # render as number
  mutate_if(is.character, as.numeric) %>%
  # show result
  glimpse()

#import B; 
novick_b <- read.csv("data/g149novickB.csv", header = FALSE) 
novick_b <- novick_b %>%   
  # separate columns and add titles;
  separate_wider_delim(1, ",", names = c("t", "concentration")) %>% 
  # render as number
  mutate_if(is.character, as.numeric) %>%
  # show result
  glimpse()

```

Visualization of Data set A

```{r a_Q1}
a_q1_graph <- novick_a %>%
  ggplot(aes(x = t, y = concentration)) + 
  geom_point() + 
  labs(
    title = "growth of beta-gal ",
    subtitle = "in response to high TMG concentration",
    x = "time (hours)", 
    y = "fraction of maximum beta-gal"
  ) 
print(a_q1_graph)
```

Fitting function on Data set A

```{r a_q2}
#define function
growth_a <- function (t, ampl, tau) (ampl*(1- exp(-(t/tau))))
  
#fit function without (0,0)
a_q2_fn <- nls(novick_a$concentration ~ growth_a(t, ampl, tau), data = novick_a, start = list(ampl = 1.26, tau = 2.62))

# store coefficients
coef_a2 <- coef(a_q2_fn)

# plot fitted curve over data
novick_a %>%
  ggplot(aes(x = t, y = concentration)) + 
  geom_point(data = novick_a) + 
  labs( 
    title = "growth of beta-gal", 
    subtitle = "in response to high TMG concentration", 
    x = "time (hours)", 
    y = "fraction of maximum beta-gal"
  )+
  stat_function(fun = growth_a, 
                args = c(ampl = coef_a2[[1]], 
                         tau = coef_a2[[2]]))
```

```{r a_q3}

#fit data with (0,0)

# add (0,0) to data
a_q3_df <- novick_a %>%
  rbind(c(0,0))
# fit data again
a_q3_fit <- nls(a_q3_df$concentration ~ growth_a(t, ampl, tau), data = a_q3_df, start = list(ampl = 1.26, tau = 2.62))

coef_a3 <- coef(a_q3_fit)

coef_comp <- coef_a2 %>% 
  rbind (coef_a3) %>%
  print()

# plot new fitted curve over data
a_q3_df %>%
  ggplot(aes(x = t, y = concentration)) + 
  geom_point(data = novick_a) + 
  labs( 
    title = "growth of beta-gal", 
    subtitle = "in response to high TMG concentration", 
    x = "time (hours)", 
    y = "fraction of maximum beta-gal"
  )+
  stat_function(fun = growth_a, 
                args = c(ampl = coef_a3[[1]], 
                         tau = coef_a3[[2]]))

```

Analysis:

Visualization of Data set B

```{r b_q1}
novick_b %>%
  ggplot(aes(x = t, y = concentration)) + 
  geom_point() + 
  labs(
    title = "growth of beta-gal", 
    subtitle = "in response to lower TMG concentration", 
    x = "time (hours)", 
    y = "fraction of maximum beta-gal"
  ) 
```

Fitting function on Data set B

```{r b_q2}
# get data for 10<=t<=15
b_q2 <- novick_b %>% 
  filter(t >= 10) %>% 
  filter(t <= 15)
# fit straight line for 10<= t <= 15

b_q2_fit <- lm(b_q2$concentration ~ b_q2$t)
coef_b2 <- coef(b_q2_fit)
  # plot
novick_b %>%
  ggplot(aes(x = t, y = concentration)) + 
  geom_point() + 
  labs(
    title = "growth of beta-gal", 
    subtitle = "in response to lower TMG concentration", 
    x = "time (hours)", 
    y = "fraction of maximum beta-gal"
  ) + 
  geom_abline(
    intercept = coef_b2[[1]], 
    slope = coef_b2[[2]])


```

```{r b_q3}
# fit function from a
# define function
growth_b3 <- function (t, ampl, tau) (ampl*(1- exp(-(t/tau))))

# fit function
b_q3 <- nls(novick_b$concentration ~ growth_b3(t, ampl, tau), data = novick_b, start = list(ampl = 0.8, tau = 100))

coef_b3 <- coef(b_q3)

# plot the fitted function
novick_b %>%
  ggplot(aes(x = t, y = concentration)) + 
  geom_point() + 
  labs( 
    title = "growth of beta-gal", 
    subtitle = "in response to lower TMG concentration", 
    x = "time (hours)", 
    y = "fraction of maximum beta-gal"
  )  +
  stat_function(fun = growth_b3, 
                args = c(ampl = coef_b3[[1]], 
                         tau = coef_b3[[2]]))
```

```{r b_q4}
# Separate data for t<= 15

b_q4_df <- novick_b %>%
  filter(t <= 15)


# define function
growth_b4 <- function (t, beta, tau) (beta * (-1 + t/tau + exp(-t/tau)))

# fit function
b_q4 <- nls(b_q4_df$concentration ~ growth_b4(t, beta, tau), data = b_q4_df, start = list(beta = 1, tau = 1))



coef_b4 <- coef(b_q4)

# plot the new fitted function
# the data of t>15 is in blue and the rest is in red

b_q4_df %>%
  ggplot(aes(x = t, y = concentration)) + 
  geom_point(aes(color = "blue")) + 
  grom_point(data = novick_b, aes(color = "red"))
  labs( 
    title = "growth of beta-gal", 
    subtitle = "in response to high TMG concentration", 
    x = "time (hours)", 
    y = "fraction of maximum beta-gal"
  )  +
  stat_function(fun = growth_b4, 
                args = c(beta = coef_b4[[1]], 
                         tau = coef_b4[[2]]))
```

Q5: at large t, the function becomes linear as -t/tau becomes 0 so exp(-t/tau) becomes a constant of 1

Analysis:
